"""add managed_runs.problem_statement

Revision ID: bf40a779a85c
Revises: fbaa083ee6c5
Create Date: 2026-08-18 20:33:13.825809

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'bf40a779a85c'
down_revision = 'fbaa083ee6c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_runs', sa.Column('problem_statement', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managed_runs', 'problem_statement')
    # ### end Alembic commands ###
