"""managed runs attempts events outbox audit

Revision ID: fbaa083ee6c5
Revises: 
Create Date: 2026-08-18 19:53:09.039844

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'fbaa083ee6c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_attempts',
    sa.Column('attempt_id', sa.String(length=26), nullable=False),
    sa.Column('run_id', sa.String(length=26), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('platform_outcome', sa.String(length=32), nullable=False),
    sa.Column('agent_outcome', sa.String(length=32), nullable=False),
    sa.Column('artifact_outcome', sa.String(length=32), nullable=False),
    sa.Column('evaluation_outcome', sa.String(length=32), nullable=False),
    sa.Column('desired_state', sa.String(length=32), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_manifest_ref', sa.String(length=512), nullable=True),
    sa.Column('cancel_after_terminal', sa.Boolean(), nullable=False),
    sa.Column('final_reason', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('attempt_id'),
    sa.UniqueConstraint('run_id', 'attempt_number', name='uq_managed_attempts_run_num')
    )
    op.create_index(op.f('ix_managed_attempts_run_id'), 'managed_attempts', ['run_id'], unique=False)
    op.create_table('managed_audit_events',
    sa.Column('sequence', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=256), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sequence')
    )
    op.create_index(op.f('ix_managed_audit_events_resource_id'), 'managed_audit_events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_managed_audit_events_tenant_id'), 'managed_audit_events', ['tenant_id'], unique=False)
    op.create_table('managed_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=26), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managed_outbox_created_at'), 'managed_outbox', ['created_at'], unique=False)
    op.create_index('ix_managed_outbox_pending', 'managed_outbox', ['processed_at', 'id'], unique=False)
    op.create_index(op.f('ix_managed_outbox_run_id'), 'managed_outbox', ['run_id'], unique=False)
    op.create_table('managed_run_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.String(length=26), nullable=False),
    sa.Column('attempt_id', sa.String(length=26), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('observed_generation', sa.Integer(), nullable=False),
    sa.Column('last_transition_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_managed_run_events_run_seq')
    )
    op.create_index(op.f('ix_managed_run_events_run_id'), 'managed_run_events', ['run_id'], unique=False)
    op.create_table('managed_runs',
    sa.Column('run_id', sa.String(length=26), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('template_ref', sa.String(length=256), nullable=False),
    sa.Column('template_revision', sa.Integer(), nullable=False),
    sa.Column('input_ref', sa.String(length=512), nullable=False),
    sa.Column('input_sha256', sa.String(length=64), nullable=False),
    sa.Column('deadline_seconds', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('desired_state', sa.String(length=32), nullable=True),
    sa.Column('current_attempt_id', sa.String(length=26), nullable=True),
    sa.Column('attempt_counter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_reason', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('run_id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_managed_runs_tenant_idemkey')
    )
    op.create_index(op.f('ix_managed_runs_project_id'), 'managed_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_managed_runs_tenant_id'), 'managed_runs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managed_runs_tenant_id'), table_name='managed_runs')
    op.drop_index(op.f('ix_managed_runs_project_id'), table_name='managed_runs')
    op.drop_table('managed_runs')
    op.drop_index(op.f('ix_managed_run_events_run_id'), table_name='managed_run_events')
    op.drop_table('managed_run_events')
    op.drop_index(op.f('ix_managed_outbox_run_id'), table_name='managed_outbox')
    op.drop_index('ix_managed_outbox_pending', table_name='managed_outbox')
    op.drop_index(op.f('ix_managed_outbox_created_at'), table_name='managed_outbox')
    op.drop_table('managed_outbox')
    op.drop_index(op.f('ix_managed_audit_events_tenant_id'), table_name='managed_audit_events')
    op.drop_index(op.f('ix_managed_audit_events_resource_id'), table_name='managed_audit_events')
    op.drop_table('managed_audit_events')
    op.drop_index(op.f('ix_managed_attempts_run_id'), table_name='managed_attempts')
    op.drop_table('managed_attempts')
    # ### end Alembic commands ###
